version: "3.9"
services:
  # Install Source MySQL DB and set up the Customer database
  mysql-1:
    container_name: source-database
    image: mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: customerdb

    #io.debezium.relational.history.DatabaseHistoryException: Unable to create history file at /tmp/dbhistory.dat: /tmp
    volumes:
      - ./mysql-1:/var/lib/mysql
      - ./dbhistory:/tmp
      - ./dbhistory:/tmp2
      - ./mysql-1/conf.d:/etc/mysql/conf.d
      - ./mysql-1/init:/docker-entrypoint-initdb.d
      - ./mysql-1/logs:/logs
      - ./mysql-1/scripts:/scripts
      - ./mysql-1/backup:/backup
      - ./mysql-1/restore:/restore
      - ./mysql-1/ssl:/ssl



  # Install Target MySQL DB and set up the Customer database
  mysql-2:
    container_name: target-database
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: customerdb

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeepers
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  broker:
      image: confluentinc/cp-kafka:7.0.1
      container_name: broker
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        kafka.bootstrap.servers: broker:9092
        GROUP_ID: group_id
        KAFKA_CREATE_TOPICS: "product"



  kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      ports:
        - "8080:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=broker
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
        - KAFKA_CLUSTERS_0_READONLY=true

    # Install Debezium MySQL Connector
  debezium-connector:
     image: debezium/connect:1.7
     container_name: debezium-connector
     ports:
        - 8083:8083
     depends_on:
        - mysql-1
        - broker
     environment:
        - BOOTSTRAP_SERVERS=broker:29092
        - GROUP_ID=1
        - CONFIG_STORAGE_TOPIC=debezium-config
        - OFFSET_STORAGE_TOPIC=debezium-offset
        - STATUS_STORAGE_TOPIC=debezium-status
        - CONFIG_STORAGE_REPLICATION_FACTOR=1
        - OFFSET_STORAGE_REPLICATION_FACTOR=1
        - STATUS_STORAGE_REPLICATION_FACTOR=1
        - KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
        - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - VALUE_CONVERTER_SCHEMAS_ENABLE=false
        - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE=false
        - INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE=false
        - OFFSET_FLUSH_INTERVAL_MS=10000
        - CONNECT_REST_PORT=8083
        - CONNECT_GROUP_ID=connect-cluster
        - CONNECT_CONFIG_STORAGE_TOPIC=connect-configs
        - CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
        - CONNECT_STATUS_STORAGE_TOPIC=connect-status
        - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
        - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
        - CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE=false
        - CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE=false
        - CONNECT_PLUGIN_PATH=/kafka/connect
        - KAFKA_CONNECT_JDBC_DIR=/kafka/connect/jdbc
        - KAFKA_CONNECT_JDBC_PLUGIN_DIR=/kafka/connect/jdbc
        - KAFKA_CONNECT_JDBC_PLUGIN_PATH=/kafka/connect/jdbc


