version: "3.9"
services:
  # Install Source MySQL DB and set up the Customer database
  mysql-1:
    container_name: source-database
    image: mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: customerdb

    #io.debezium.relational.history.DatabaseHistoryException: Unable to create history file at /tmp/dbhistory.dat: /tmp
    volumes:
      - ./mysql-1:/var/lib/mysql
      - ./dbhistory:/tmp
      - ./dbhistory:/tmp2
      - ./mysql-1/conf.d:/etc/mysql/conf.d
      - ./mysql-1/init:/docker-entrypoint-initdb.d
      - ./mysql-1/logs:/logs
      - ./mysql-1/scripts:/scripts
      - ./mysql-1/backup:/backup
      - ./mysql-1/restore:/restore
      - ./mysql-1/ssl:/ssl


